#include <stdio.h>
void auto_show_compile_options(void) {
   FILE *opf;
   opf = fopen("Enzo_Build", "w");
   fprintf(opf, "### Enzo build information:\n");
   fprintf(opf, "### Compiled: Sun Feb 12 16:17:50 2017\n");
   fprintf(opf, "### Machine name: linux-gnu\n");
   fprintf(opf, "### Branch: (week-of-code)\n");
   fprintf(opf, "### Changeset: 240af05dd312+\n");
   fprintf(opf, "###\n");
   fprintf(opf, "### Enzo was built with uncommitted changes.\n");
   fprintf(opf, "### Check Enzo_Build_Diff to see the output of hg diff.\n");
   fprintf(opf, "###\n");
   fprintf(opf, "### Use this as a compile settings file by renaming\n");
   fprintf(opf, "### it Make.settings.<keyword> and moving it to\n");
   fprintf(opf, "### either src/enzo or .enzo in your home directory.\n");
   fprintf(opf, "### Then, type \"make load-config-<keyword>\" to load\n");
   fprintf(opf, "### compiler options.\n");
   fprintf(opf, "###\n");
   fprintf(opf, "### The current compile options are shown below.\n");
   fprintf(opf, "### For more information on the meaning of the\n");
   fprintf(opf, "### options, consult src/enzo/Make.config.settings.\n");
   fprintf(opf, "\n");
   fprintf(opf, "PARAMETER_MAX_SUBGRIDS = 100000\n");
   fprintf(opf, "PARAMETER_MAX_BARYONS = 30\n");
   fprintf(opf, "PARAMETER_MAX_TASKS_PER_NODE = 8\n");
   fprintf(opf, "PARAMETER_MEMORY_POOL_SIZE = 100000\n");
   fprintf(opf, "CONFIG_INTEGERS = 64\n");
   fprintf(opf, "CONFIG_PARTICLE_IDS = 64\n");
   fprintf(opf, "CONFIG_PRECISION = 64\n");
   fprintf(opf, "CONFIG_PARTICLES = 64\n");
   fprintf(opf, "CONFIG_INITS = 64\n");
   fprintf(opf, "CONFIG_IO = 32\n");
   fprintf(opf, "CONFIG_USE_MPI = yes\n");
   fprintf(opf, "CONFIG_OBJECT_MODE = 64\n");
   fprintf(opf, "CONFIG_TASKMAP = no\n");
   fprintf(opf, "CONFIG_PACKED_AMR = yes\n");
   fprintf(opf, "CONFIG_PACKED_MEM = no\n");
   fprintf(opf, "CONFIG_LCAPERF = no\n");
   fprintf(opf, "CONFIG_PAPI = no\n");
   fprintf(opf, "CONFIG_PYTHON = no\n");
   fprintf(opf, "CONFIG_NEW_PROBLEM_TYPES = no\n");
   fprintf(opf, "CONFIG_OOC_BOUNDARY = no\n");
   fprintf(opf, "CONFIG_ACCELERATION_BOUNDARY = yes\n");
   fprintf(opf, "CONFIG_ENZO_PERFORMANCE = yes\n");
   fprintf(opf, "CONFIG_OPT = high\n");
   fprintf(opf, "CONFIG_TESTING = no\n");
   fprintf(opf, "CONFIG_PHOTON = yes\n");
   fprintf(opf, "CONFIG_HYPRE = no\n");
   fprintf(opf, "CONFIG_EMISSIVITY = no\n");
   fprintf(opf, "CONFIG_NEW_GRID_IO = yes\n");
   fprintf(opf, "CONFIG_FAST_SIB = yes\n");
   fprintf(opf, "CONFIG_USE_HDF4 = no\n");
   fprintf(opf, "CONFIG_BITWISE_IDENTICALITY = no\n");
   fprintf(opf, "CONFIG_ECUDA = no\n");
   fprintf(opf, "CONFIG_GRAVITY_4S = no\n");
   fprintf(opf, "CONFIG_GRACKLE = yes\n");
   fprintf(opf, "CONFIG_LOG2ALLOC = no\n");
   fclose(opf);

   opf = fopen("Enzo_Build_Diff", "w");
   fprintf(opf, "diff -r 240af05dd312 src/enzo/EvolveLevel.C\n");
   fprintf(opf, "--- a/src/enzo/EvolveLevel.C	Wed Dec 14 11:11:05 2016 -0500\n");
   fprintf(opf, "+++ b/src/enzo/EvolveLevel.C	Sun Feb 12 16:17:50 2017 -0500\n");
   fprintf(opf, "@@ -39,7 +39,6 @@\n");
   fprintf(opf, " /                computing the timestep, output, handling fluxes\n");
   fprintf(opf, " /  modified10: July, 2009 by Sam Skillman\n");
   fprintf(opf, " /                Added shock analysis\n");
   fprintf(opf, "-/\n");
   fprintf(opf, " /  PURPOSE:\n");
   fprintf(opf, " /    This routine is the main grid evolution function.  It assumes that the\n");
   fprintf(opf, " /    grids of level-1 have already been advanced by dt (passed\n");
   fprintf(opf, "@@ -608,6 +607,10 @@\n");
   fprintf(opf, "  \n");
   fprintf(opf, "       if (ComovingCoordinates)\n");
   fprintf(opf, " 	Grids[grid1]->GridData->ComovingExpansionTerms();\n");
   fprintf(opf, "+	\n");
   fprintf(opf, "+	  /* If using floors, reset fields based on foors*/\n");
   fprintf(opf, "+	  if (UseFloor)\n");
   fprintf(opf, "+			Grids[grid1]->GridData->SetFloor_EvolveLevel();\n");
   fprintf(opf, "  \n");
   fprintf(opf, "     }  // end loop over grids\n");
   fprintf(opf, "  \n");
   fprintf(opf, "diff -r 240af05dd312 src/enzo/EvolvePhotons.C\n");
   fprintf(opf, "--- a/src/enzo/EvolvePhotons.C	Wed Dec 14 11:11:05 2016 -0500\n");
   fprintf(opf, "+++ b/src/enzo/EvolvePhotons.C	Sun Feb 12 16:17:50 2017 -0500\n");
   fprintf(opf, "@@ -590,7 +590,7 @@\n");
   fprintf(opf, " \n");
   fprintf(opf, " 	    int RTCoupledSolverIntermediateStep = TRUE;\n");
   fprintf(opf, " \n");
   fprintf(opf, "-#ifdef USE_GRACKLE\n");
   fprintf(opf, "+/*#ifdef USE_GRACKLE\n");
   fprintf(opf, "             if (grackle_data->use_grackle == TRUE){\n");
   fprintf(opf, "               grackle_data->radiative_transfer_intermediate_step = (Eint32) RTCoupledSolverIntermediateStep;\n");
   fprintf(opf, " \n");
   fprintf(opf, "@@ -599,7 +599,7 @@\n");
   fprintf(opf, "               }\n");
   fprintf(opf, "               continue;\n");
   fprintf(opf, "             }\n");
   fprintf(opf, "-#endif // USE_GRACKLE\n");
   fprintf(opf, "+#endif // USE_GRACKLE*/ // OLDHC\n");
   fprintf(opf, " \n");
   fprintf(opf, " 	    Temp->GridData->SolveRateAndCoolEquations(RTCoupledSolverIntermediateStep);\n");
   fprintf(opf, " \n");
   fprintf(opf, "diff -r 240af05dd312 src/enzo/Grid.h\n");
   fprintf(opf, "--- a/src/enzo/Grid.h	Wed Dec 14 11:11:05 2016 -0500\n");
   fprintf(opf, "+++ b/src/enzo/Grid.h	Sun Feb 12 16:17:50 2017 -0500\n");
   fprintf(opf, "@@ -571,7 +571,8 @@\n");
   fprintf(opf, " \n");
   fprintf(opf, " /* Baryons: compute the cooling time. */\n");
   fprintf(opf, " \n");
   fprintf(opf, "-   int ComputeCoolingTime(float *cooling_time, int CoolingTimeOnly=FALSE);\n");
   fprintf(opf, "+   int ComputeCoolingTime(float *cooling_time); //old version grackle\n");
   fprintf(opf, "+   //int ComputeCoolingTime(float *cooling_time, int CoolingTimeOnly=FALSE);\n");
   fprintf(opf, " \n");
   fprintf(opf, " /* Baryons & DualEnergyFormalism: Restore consistency between total and\n");
   fprintf(opf, "                                   internal energy fields. */\n");
   fprintf(opf, "@@ -1695,6 +1696,9 @@\n");
   fprintf(opf, "   int IdentifyPhysicalQuantities(int &DensNum, int &GENum, int &Vel1Num,\n");
   fprintf(opf, " 				 int &Vel2Num, int &Vel3Num, int &TENum,\n");
   fprintf(opf, " 				 int &B1Num, int &B2Num, int &B3Num, int &PhiNum, int &CRNum);\n");
   fprintf(opf, "+  // for Heating/Cooling\n");
   fprintf(opf, "+  int IdentifyPhysicalQuantities(int &DensNum, int &GENum, int &Vel1Num,\n");
   fprintf(opf, "+				     int &Vel2Num, int &Vel3Num, int &TENum, int &G0Num, int &ZetaNum);\n");
   fprintf(opf, " \n");
   fprintf(opf, "   /* Identify driving fields */\n");
   fprintf(opf, " \n");
   fprintf(opf, "@@ -2177,6 +2181,25 @@\n");
   fprintf(opf, " 			  FLOAT SubDomainRightEdge[],\n");
   fprintf(opf, " 			  float CosmologySimulationInitialUniformBField[]);\n");
   fprintf(opf, " \n");
   fprintf(opf, "+  /* Initialization for isolated galaxy disk */\n");
   fprintf(opf, "+  int MyGalaxyInitializeGrid(\n");
   fprintf(opf, "+              FLOAT DiskRadius,\n");
   fprintf(opf, "+              float CircularVelocity,\n");
   fprintf(opf, "+              float GasMass,\n");
   fprintf(opf, "+              FLOAT DiskPosition[MAX_DIMENSION],\n");
   fprintf(opf, "+              FLOAT ScaleHeightz,\n");
   fprintf(opf, "+              FLOAT ScaleHeightR,\n");
   fprintf(opf, "+              float DiskTemperature,\n");
   fprintf(opf, "+              float InitialTemperature,\n");
   fprintf(opf, "+              float AngularMomentum[MAX_DIMENSION],\n");
   fprintf(opf, "+              float UniformVelocity[MAX_DIMENSION],\n");
   fprintf(opf, "+              float AmbientDensity,\n");
   fprintf(opf, "+              int UseMetallicityField,\n");
   fprintf(opf, "+              float GalaxySimulationInflowTime,\n");
   fprintf(opf, "+              float GalaxySimulationInflowDensity,\n");
   fprintf(opf, "+			  int GalaxySimulationB0FieldFlag,\n");
   fprintf(opf, "+			  float GalaxySimulationB0FieldStrength,\n");
   fprintf(opf, "+              int level);\n");
   fprintf(opf, " \n");
   fprintf(opf, "   /* Initialization for isolated galaxy sims */\n");
   fprintf(opf, "   int GalaxySimulationInitializeGrid(\n");
   fprintf(opf, "@@ -2836,7 +2859,7 @@\n");
   fprintf(opf, "   int SaveMHDSubgridFluxes(fluxes *SubgridFluxes[], int NumberOfSubgrids,\n");
   fprintf(opf, " 			   float *Flux3D[], int flux, float fluxcoef, float dt);\n");
   fprintf(opf, "   int SetFloor();\n");
   fprintf(opf, "-\n");
   fprintf(opf, "+  int SetFloor_EvolveLevel();\n");
   fprintf(opf, " \n");
   fprintf(opf, "   /* Poisson clean routines */\n");
   fprintf(opf, " \n");
   fprintf(opf, "diff -r 240af05dd312 src/enzo/Grid_ComputeCoolingTime.C\n");
   fprintf(opf, "--- a/src/enzo/Grid_ComputeCoolingTime.C	Wed Dec 14 11:11:05 2016 -0500\n");
   fprintf(opf, "+++ b/src/enzo/Grid_ComputeCoolingTime.C	Sun Feb 12 16:17:50 2017 -0500\n");
   fprintf(opf, "@@ -14,7 +14,7 @@\n");
   fprintf(opf, " ************************************************************************/\n");
   fprintf(opf, "  \n");
   fprintf(opf, " // Compute the cooling time\n");
   fprintf(opf, "-\n");
   fprintf(opf, "+ \n");
   fprintf(opf, " #include \"preincludes.h\"\n");
   fprintf(opf, " #include \"macros_and_parameters.h\"\n");
   fprintf(opf, " #include \"typedefs.h\"\n");
   fprintf(opf, "@@ -53,13 +53,13 @@\n");
   fprintf(opf, " extern \"C\" void FORTRAN_NAME(cool_multi_time)(\n");
   fprintf(opf, " 	float *d, float *e, float *ge, float *u, float *v, float *w, float *de,\n");
   fprintf(opf, " 	float *HI, float *HII, float *HeI, float *HeII, float *HeIII,\n");
   fprintf(opf, "-	float *cooltime, int *coolonly,\n");
   fprintf(opf, "+	float *cooltime,\n");
   fprintf(opf, " 	int *in, int *jn, int *kn, int *nratec, int *iexpand,\n");
   fprintf(opf, " 	hydro_method *imethod,\n");
   fprintf(opf, "         int *idual, int *ispecies, int *imetal, int *imcool, int *idust, int *idim,\n");
   fprintf(opf, " 	int *is, int *js, int *ks, int *ie, int *je, int *ke, int *ih2co,\n");
   fprintf(opf, " 	int *ipiht, int *igammah,\n");
   fprintf(opf, "-	float *dt, float *aye, float *redshift, float *temstart, float *temend,\n");
   fprintf(opf, "+	float *dt, float *aye, float *temstart, float *temend,\n");
   fprintf(opf, " 	float *utem, float *uxyz, float *uaye, float *urho, float *utim,\n");
   fprintf(opf, " 	float *eta1, float *eta2, float *gamma, float *z_solar,\n");
   fprintf(opf, " 	float *ceHIa, float *ceHeIa, float *ceHeIIa, float *ciHIa, float *ciHeIa,\n");
   fprintf(opf, "@@ -90,7 +90,7 @@\n");
   fprintf(opf, " 	float *fh, float *utem, float *urho, \n");
   fprintf(opf, " 	float *eta1, float *eta2, float *gamma, float *coola, float *gammaha, float *mu);\n");
   fprintf(opf, "  \n");
   fprintf(opf, "-int grid::ComputeCoolingTime(float *cooling_time, int CoolingTimeOnly)\n");
   fprintf(opf, "+int grid::ComputeCoolingTime(float *cooling_time)\n");
   fprintf(opf, " {\n");
   fprintf(opf, "  \n");
   fprintf(opf, "   /* Return if this doesn't concern us. */\n");
   fprintf(opf, "@@ -101,7 +101,7 @@\n");
   fprintf(opf, "     return SUCCESS;\n");
   fprintf(opf, "  \n");
   fprintf(opf, "   int DeNum, HINum, HIINum, HeINum, HeIINum, HeIIINum, HMNum, H2INum, H2IINum,\n");
   fprintf(opf, "-      DINum, DIINum, HDINum, DensNum, GENum, Vel1Num, Vel2Num, Vel3Num, TENum;\n");
   fprintf(opf, "+      DINum, DIINum, HDINum, DensNum, GENum, Vel1Num, Vel2Num, Vel3Num, TENum,G0Num,ZetaNum;\n");
   fprintf(opf, "  \n");
   fprintf(opf, "   /* Compute the size of the fields. */\n");
   fprintf(opf, "  \n");
   fprintf(opf, "@@ -113,7 +113,7 @@\n");
   fprintf(opf, "   /* Find fields: density, total energy, velocity1-3. */\n");
   fprintf(opf, "  \n");
   fprintf(opf, "   if (this->IdentifyPhysicalQuantities(DensNum, GENum, Vel1Num, Vel2Num,\n");
   fprintf(opf, "-				       Vel3Num, TENum) == FAIL) {\n");
   fprintf(opf, "+				       Vel3Num, TENum, G0Num, ZetaNum) == FAIL) {\n");
   fprintf(opf, "     ENZO_FAIL(\"Error in IdentifyPhysicalQuantities.\\n\");\n");
   fprintf(opf, "   }\n");
   fprintf(opf, "  \n");
   fprintf(opf, "@@ -143,10 +143,8 @@\n");
   fprintf(opf, "   float *velocity1   = BaryonField[Vel1Num];\n");
   fprintf(opf, "   float *velocity2   = BaryonField[Vel2Num];\n");
   fprintf(opf, "   float *velocity3   = BaryonField[Vel3Num];\n");
   fprintf(opf, "-\n");
   fprintf(opf, "-  float *volumetric_heating_rate = NULL;\n");
   fprintf(opf, "-  float *specific_heating_rate   = NULL;\n");
   fprintf(opf, "- \n");
   fprintf(opf, "+  float *fuv_G0      = BaryonField[G0Num];\n");
   fprintf(opf, "+  float *cr_Zeta      = BaryonField[ZetaNum];\n");
   fprintf(opf, "   /* Compute the cooling time. */\n");
   fprintf(opf, "  \n");
   fprintf(opf, "   FLOAT a = 1.0, dadt;\n");
   fprintf(opf, "@@ -159,9 +157,6 @@\n");
   fprintf(opf, "     CosmologyComputeExpansionFactor(Time+0.5*dtFixed, &a, &dadt);\n");
   fprintf(opf, "  \n");
   fprintf(opf, "     aUnits = 1.0/(1.0 + InitialRedshift);\n");
   fprintf(opf, "-  } else if (RadiationFieldRedshift > -1){\n");
   fprintf(opf, "-    a       = 1.0 / (1.0 + RadiationFieldRedshift);\n");
   fprintf(opf, "-    aUnits  = 1.0;\n");
   fprintf(opf, "   }\n");
   fprintf(opf, "   float afloat = float(a);\n");
   fprintf(opf, "  \n");
   fprintf(opf, "@@ -187,7 +182,7 @@\n");
   fprintf(opf, "   /* If both metal fields (Pop I/II and III) exist, create a field\n");
   fprintf(opf, "      that contains their sum */\n");
   fprintf(opf, " \n");
   fprintf(opf, "-  float *MetalPointer = NULL;\n");
   fprintf(opf, "+  float *MetalPointer;\n");
   fprintf(opf, "   float *TotalMetals = NULL;\n");
   fprintf(opf, " \n");
   fprintf(opf, "   if (MetalNum != -1 && SNColourNum != -1) {\n");
   fprintf(opf, "@@ -204,35 +199,34 @@\n");
   fprintf(opf, "   } // ENDELSE both metal types\n");
   fprintf(opf, "  \n");
   fprintf(opf, " #ifdef USE_GRACKLE\n");
   fprintf(opf, "-  if (grackle_data->use_grackle == TRUE) {\n");
   fprintf(opf, "-\n");
   fprintf(opf, "-    Eint32 *g_grid_dimension, *g_grid_start, *g_grid_end;\n");
   fprintf(opf, "-    g_grid_dimension = new Eint32[GridRank];\n");
   fprintf(opf, "-    g_grid_start = new Eint32[GridRank];\n");
   fprintf(opf, "-    g_grid_end = new Eint32[GridRank];\n");
   fprintf(opf, "-    for (i = 0; i < GridRank; i++) {\n");
   fprintf(opf, "-      g_grid_dimension[i] = (Eint32) GridDimension[i];\n");
   fprintf(opf, "-      g_grid_start[i] = (Eint32) GridStartIndex[i];\n");
   fprintf(opf, "-      g_grid_end[i] = (Eint32) GridEndIndex[i];\n");
   fprintf(opf, "-    }\n");
   fprintf(opf, "+    if (grackle_data.use_grackle == TRUE) {\n");
   fprintf(opf, "+        \n");
   fprintf(opf, "+            Eint32 *g_grid_dimension, *g_grid_start, *g_grid_end;\n");
   fprintf(opf, "+            g_grid_dimension = new Eint32[GridRank];\n");
   fprintf(opf, "+            g_grid_start = new Eint32[GridRank];\n");
   fprintf(opf, "+            g_grid_end = new Eint32[GridRank];\n");
   fprintf(opf, "+            for (i = 0; i < GridRank; i++) {\n");
   fprintf(opf, "+                  g_grid_dimension[i] = (Eint32) GridDimension[i];\n");
   fprintf(opf, "+                  g_grid_start[i] = (Eint32) GridStartIndex[i];\n");
   fprintf(opf, "+                  g_grid_end[i] = (Eint32) GridEndIndex[i];\n");
   fprintf(opf, "+            }\n");
   fprintf(opf, " \n");
   fprintf(opf, "     /* Update units. */\n");
   fprintf(opf, " \n");
   fprintf(opf, "-    code_units grackle_units;\n");
   fprintf(opf, "-    grackle_units.comoving_coordinates = (Eint32) ComovingCoordinates;\n");
   fprintf(opf, "-    grackle_units.density_units        = (double) DensityUnits;\n");
   fprintf(opf, "-    grackle_units.length_units         = (double) LengthUnits;\n");
   fprintf(opf, "-    grackle_units.time_units           = (double) TimeUnits;\n");
   fprintf(opf, "-    grackle_units.velocity_units       = (double) VelocityUnits;\n");
   fprintf(opf, "-    grackle_units.a_units              = (double) aUnits;\n");
   fprintf(opf, "-    grackle_units.a_value              = (double) a;\n");
   fprintf(opf, "-\n");
   fprintf(opf, "+            code_units grackle_units;\n");
   fprintf(opf, "+            grackle_units.comoving_coordinates = (Eint32) ComovingCoordinates;\n");
   fprintf(opf, "+            grackle_units.density_units        = (double) DensityUnits;\n");
   fprintf(opf, "+            grackle_units.length_units         = (double) LengthUnits;\n");
   fprintf(opf, "+            grackle_units.time_units           = (double) TimeUnits;\n");
   fprintf(opf, "+            grackle_units.velocity_units       = (double) VelocityUnits;\n");
   fprintf(opf, "+            grackle_units.a_units              = (double) aUnits;\n");
   fprintf(opf, "+   \n");
   fprintf(opf, "     int temp_thermal = FALSE;\n");
   fprintf(opf, "     float *thermal_energy;\n");
   fprintf(opf, "-    if ( UseMHD ){\n");
   fprintf(opf, "+    if (HydroMethod == MHD_RK){\n");
   fprintf(opf, "       iBx = FindField(Bfield1, FieldType, NumberOfBaryonFields);\n");
   fprintf(opf, "       iBy = FindField(Bfield2, FieldType, NumberOfBaryonFields);\n");
   fprintf(opf, "-      iBz = FindField(Bfield3, FieldType, NumberOfBaryonFields);\n");
   fprintf(opf, "+      iBz = FindField(Bfield3, FieldType, NumberOfBaryonFields);  \n");
   fprintf(opf, "     }\n");
   fprintf(opf, " \n");
   fprintf(opf, "     if (HydroMethod==Zeus_Hydro) {\n");
   fprintf(opf, "@@ -252,7 +246,7 @@\n");
   fprintf(opf, "         if(GridRank > 2)\n");
   fprintf(opf, "           thermal_energy[i] -= 0.5 * POW(BaryonField[Vel3Num][i], 2.0);\n");
   fprintf(opf, " \n");
   fprintf(opf, "-        if( UseMHD ) {\n");
   fprintf(opf, "+        if(HydroMethod == MHD_RK) {\n");
   fprintf(opf, "           thermal_energy[i] -= 0.5 * (POW(BaryonField[iBx][i], 2.0) + \n");
   fprintf(opf, "                                       POW(BaryonField[iBy][i], 2.0) + \n");
   fprintf(opf, "                                       POW(BaryonField[iBz][i], 2.0)) / \n");
   fprintf(opf, "@@ -261,91 +255,35 @@\n");
   fprintf(opf, "       } // for (int i = 0; i < size; i++)\n");
   fprintf(opf, "     }\n");
   fprintf(opf, " \n");
   fprintf(opf, "-    /* set up the my_fields */\n");
   fprintf(opf, "-    grackle_field_data my_fields;\n");
   fprintf(opf, "-\n");
   fprintf(opf, "-    my_fields.grid_rank = (Eint32) GridRank;\n");
   fprintf(opf, "-    my_fields.grid_dimension = g_grid_dimension;\n");
   fprintf(opf, "-    my_fields.grid_start     = g_grid_start;\n");
   fprintf(opf, "-    my_fields.grid_end       = g_grid_end;\n");
   fprintf(opf, "-\n");
   fprintf(opf, "-    /* now add in the baryon fields */\n");
   fprintf(opf, "-    my_fields.density         = density;\n");
   fprintf(opf, "-    my_fields.internal_energy = thermal_energy;\n");
   fprintf(opf, "-    my_fields.x_velocity      = velocity1;\n");
   fprintf(opf, "-    my_fields.y_velocity      = velocity2;\n");
   fprintf(opf, "-    my_fields.z_velocity      = velocity3;\n");
   fprintf(opf, "-\n");
   fprintf(opf, "-    my_fields.HI_density      = BaryonField[HINum];\n");
   fprintf(opf, "-    my_fields.HII_density     = BaryonField[HIINum];\n");
   fprintf(opf, "-    my_fields.HeI_density     = BaryonField[HeINum];\n");
   fprintf(opf, "-    my_fields.HeII_density    = BaryonField[HeIINum];\n");
   fprintf(opf, "-    my_fields.HeIII_density   = BaryonField[HeIIINum];\n");
   fprintf(opf, "-    my_fields.e_density       = BaryonField[DeNum];\n");
   fprintf(opf, "-\n");
   fprintf(opf, "-    my_fields.HM_density      = BaryonField[HMNum];\n");
   fprintf(opf, "-    my_fields.H2I_density     = BaryonField[H2INum];\n");
   fprintf(opf, "-    my_fields.H2II_density    = BaryonField[H2IINum];\n");
   fprintf(opf, "-\n");
   fprintf(opf, "-    my_fields.DI_density      = BaryonField[DINum];\n");
   fprintf(opf, "-    my_fields.DII_density     = BaryonField[DIINum];\n");
   fprintf(opf, "-    my_fields.HDI_density     = BaryonField[HDINum];\n");
   fprintf(opf, "-\n");
   fprintf(opf, "-    my_fields.metal_density   = MetalPointer;\n");
   fprintf(opf, "-\n");
   fprintf(opf, "-    my_fields.volumetric_heating_rate  = volumetric_heating_rate;\n");
   fprintf(opf, "-    my_fields.specific_heating_rate    = specific_heating_rate;\n");
   fprintf(opf, "-\n");
   fprintf(opf, "-#ifdef TRANSFER\n");
   fprintf(opf, "-\n");
   fprintf(opf, "-    /* unit conversion from Enzo RT units to CGS */\n");
   fprintf(opf, "-    const float ev2erg = 1.60217653E-12;\n");
   fprintf(opf, "-    float rtunits = ev2erg / TimeUnits;\n");
   fprintf(opf, "-\n");
   fprintf(opf, "-    if ( RadiativeTransfer ){\n");
   fprintf(opf, "-      my_fields.RT_HI_ionization_rate = BaryonField[kphHINum];\n");
   fprintf(opf, "-\n");
   fprintf(opf, "-      if (RadiativeTransferHydrogenOnly == FALSE){\n");
   fprintf(opf, "-        my_fields.RT_HeI_ionization_rate  = BaryonField[kphHeINum];\n");
   fprintf(opf, "-        my_fields.RT_HeII_ionization_rate = BaryonField[kphHeIINum];\n");
   fprintf(opf, "-      }\n");
   fprintf(opf, "-\n");
   fprintf(opf, "-      if (MultiSpecies > 1)\n");
   fprintf(opf, "-        my_fields.RT_H2_dissociation_rate = BaryonField[kdissH2INum];\n");
   fprintf(opf, "-\n");
   fprintf(opf, "-      /* need to convert to CGS units */\n");
   fprintf(opf, "-      for( i = 0; i < size; i++) BaryonField[gammaNum][i] *= rtunits;\n");
   fprintf(opf, "-\n");
   fprintf(opf, "-      my_fields.RT_heating_rate = BaryonField[gammaNum];\n");
   fprintf(opf, "-\n");
   fprintf(opf, "-    }\n");
   fprintf(opf, "-#endif // TRANSFER\n");
   fprintf(opf, "-\n");
   fprintf(opf, "-    if (calculate_cooling_time(&grackle_units, &my_fields, cooling_time) == FAIL) {\n");
   fprintf(opf, "+        if (calculate_cooling_time(&grackle_units,\n");
   fprintf(opf, "+                               (double) afloat,\n");
   fprintf(opf, "+                               (Eint32) GridRank, g_grid_dimension,\n");
   fprintf(opf, "+                               g_grid_start, g_grid_end,\n");
   fprintf(opf, "+                               density, thermal_energy,\n");
   fprintf(opf, "+                               velocity1, velocity2, velocity3, fuv_G0, cr_Zeta, //!!! Here\n");
   fprintf(opf, "+                               BaryonField[HINum],   BaryonField[HIINum], \n");
   fprintf(opf, "+                               BaryonField[HMNum],   BaryonField[HeINum], \n");
   fprintf(opf, "+                               BaryonField[HeIINum], BaryonField[HeIIINum],\n");
   fprintf(opf, "+                               BaryonField[H2INum],  BaryonField[H2IINum],\n");
   fprintf(opf, "+                               BaryonField[DINum],   BaryonField[DIINum], \n");
   fprintf(opf, "+                               BaryonField[HDINum],  BaryonField[DeNum], \n");
   fprintf(opf, "+                               MetalPointer, cooling_time) == FAIL) {\n");
   fprintf(opf, "       ENZO_FAIL(\"Error in Grackle calculate_cooling_time.\\n\");\n");
   fprintf(opf, "     }\n");
   fprintf(opf, " \n");
   fprintf(opf, "     for (i = 0; i < size; i++) {\n");
   fprintf(opf, "       cooling_time[i] = fabs(cooling_time[i]);\n");
   fprintf(opf, "     }\n");
   fprintf(opf, "-\n");
   fprintf(opf, "+        \n");
   fprintf(opf, "     if (temp_thermal == TRUE) {\n");
   fprintf(opf, "       delete [] thermal_energy;\n");
   fprintf(opf, "     }\n");
   fprintf(opf, " \n");
   fprintf(opf, "-#ifdef TRANSFER\n");
   fprintf(opf, "-  if (RadiativeTransfer){\n");
   fprintf(opf, "-    /* convert the RT units back to Enzo */\n");
   fprintf(opf, "-    for(i = 0; i < size; i ++) BaryonField[gammaNum][i] /= rtunits;\n");
   fprintf(opf, "-\n");
   fprintf(opf, "-  }\n");
   fprintf(opf, "-#endif // TRANSFER\n");
   fprintf(opf, "-\n");
   fprintf(opf, "     delete [] TotalMetals;\n");
   fprintf(opf, "     delete [] g_grid_dimension;\n");
   fprintf(opf, "     delete [] g_grid_start;\n");
   fprintf(opf, "     delete [] g_grid_end;\n");
   fprintf(opf, "-\n");
   fprintf(opf, "+        \n");
   fprintf(opf, "     return SUCCESS;\n");
   fprintf(opf, "   }\n");
   fprintf(opf, " #endif // USE_GRACKLE\n");
   fprintf(opf, "@@ -415,7 +353,7 @@\n");
   fprintf(opf, "        density, totalenergy, gasenergy, velocity1, velocity2, velocity3,\n");
   fprintf(opf, "        BaryonField[DeNum], BaryonField[HINum], BaryonField[HIINum],\n");
   fprintf(opf, "        BaryonField[HeINum], BaryonField[HeIINum], BaryonField[HeIIINum],\n");
   fprintf(opf, "-       cooling_time, &CoolingTimeOnly,\n");
   fprintf(opf, "+       cooling_time,\n");
   fprintf(opf, "        GridDimension, GridDimension+1, GridDimension+2,\n");
   fprintf(opf, "        &CoolData.NumberOfTemperatureBins, &ComovingCoordinates,\n");
   fprintf(opf, "        &HydroMethod,\n");
   fprintf(opf, "@@ -424,8 +362,8 @@\n");
   fprintf(opf, "        &GridRank, GridStartIndex, GridStartIndex+1, GridStartIndex+2,\n");
   fprintf(opf, "        GridEndIndex, GridEndIndex+1, GridEndIndex+2,\n");
   fprintf(opf, "        &CoolData.ih2co, &CoolData.ipiht, &PhotoelectricHeating,\n");
   fprintf(opf, "-       &dtFixed, &afloat, &RadiationFieldRedshift,\n");
   fprintf(opf, "-       &CoolData.TemperatureStart, &CoolData.TemperatureEnd,\n");
   fprintf(opf, "+       &dtFixed, &afloat, &CoolData.TemperatureStart,\n");
   fprintf(opf, "+       &CoolData.TemperatureEnd,\n");
   fprintf(opf, "        &TemperatureUnits, &LengthUnits, &aUnits, &DensityUnits, &TimeUnits,\n");
   fprintf(opf, "        &DualEnergyFormalismEta1, &DualEnergyFormalismEta2, &Gamma,\n");
   fprintf(opf, "        &CoolData.SolarMetalFractionByMass,\n");
   fprintf(opf, "diff -r 240af05dd312 src/enzo/Grid_ComputeTimeStep.C\n");
   fprintf(opf, "--- a/src/enzo/Grid_ComputeTimeStep.C	Wed Dec 14 11:11:05 2016 -0500\n");
   fprintf(opf, "+++ b/src/enzo/Grid_ComputeTimeStep.C	Sun Feb 12 16:17:50 2017 -0500\n");
   fprintf(opf, "@@ -426,7 +426,7 @@\n");
   fprintf(opf, "   /* Cooling time */\n");
   fprintf(opf, "   if (UseCoolingTimestep == TRUE) {\n");
   fprintf(opf, "     float *cooling_time = new float[size];\n");
   fprintf(opf, "-    if (this->ComputeCoolingTime(cooling_time, TRUE) == FAIL) {\n");
   fprintf(opf, "+    if (this->ComputeCoolingTime(cooling_time) == FAIL) { // OLDHC\n");
   fprintf(opf, "       ENZO_FAIL(\"Error in grid->ComputeCoolingTime.\\n\");\n");
   fprintf(opf, "     }\n");
   fprintf(opf, " \n");
   fprintf(opf, "diff -r 240af05dd312 src/enzo/Grid_GrackleWrapper.C\n");
   fprintf(opf, "--- a/src/enzo/Grid_GrackleWrapper.C	Wed Dec 14 11:11:05 2016 -0500\n");
   fprintf(opf, "+++ b/src/enzo/Grid_GrackleWrapper.C	Sun Feb 12 16:17:50 2017 -0500\n");
   fprintf(opf, "@@ -36,7 +36,7 @@\n");
   fprintf(opf, " {\n");
   fprintf(opf, " \n");
   fprintf(opf, " #ifdef USE_GRACKLE\n");
   fprintf(opf, "-  if (grackle_data->use_grackle == FALSE)\n");
   fprintf(opf, "+  if (grackle_data.use_grackle == FALSE)\n");
   fprintf(opf, "     return SUCCESS;\n");
   fprintf(opf, " \n");
   fprintf(opf, "   if (ProcessorNumber != MyProcessorNumber)\n");
   fprintf(opf, "@@ -45,7 +45,7 @@\n");
   fprintf(opf, "   LCAPERF_START(\"grid_GrackleWrapper\");\n");
   fprintf(opf, " \n");
   fprintf(opf, "   int DeNum, HINum, HIINum, HeINum, HeIINum, HeIIINum, HMNum, H2INum, H2IINum,\n");
   fprintf(opf, "-      DINum, DIINum, HDINum, DensNum, GENum, Vel1Num, Vel2Num, Vel3Num, TENum;\n");
   fprintf(opf, "+      DINum, DIINum, HDINum, DensNum, GENum, Vel1Num, Vel2Num, Vel3Num, TENum,G0Num,ZetaNum;\n");
   fprintf(opf, "  \n");
   fprintf(opf, "   /* Compute the size of the fields. */\n");
   fprintf(opf, "  \n");
   fprintf(opf, "@@ -53,21 +53,21 @@\n");
   fprintf(opf, "   int size = 1;\n");
   fprintf(opf, "   for (int dim = 0; dim < GridRank; dim++)\n");
   fprintf(opf, "     size *= GridDimension[dim];\n");
   fprintf(opf, "-\n");
   fprintf(opf, "-  Eint32 *g_grid_dimension, *g_grid_start, *g_grid_end;\n");
   fprintf(opf, "-  g_grid_dimension = new Eint32[GridRank];\n");
   fprintf(opf, "-  g_grid_start = new Eint32[GridRank];\n");
   fprintf(opf, "-  g_grid_end = new Eint32[GridRank];\n");
   fprintf(opf, "-  for (i = 0; i < GridRank; i++) {\n");
   fprintf(opf, "-    g_grid_dimension[i] = (Eint32) GridDimension[i];\n");
   fprintf(opf, "-    g_grid_start[i] = (Eint32) GridStartIndex[i];\n");
   fprintf(opf, "-    g_grid_end[i] = (Eint32) GridEndIndex[i];\n");
   fprintf(opf, "-  }\n");
   fprintf(opf, "- \n");
   fprintf(opf, "+    \n");
   fprintf(opf, "+    Eint32 *g_grid_dimension, *g_grid_start, *g_grid_end;\n");
   fprintf(opf, "+    g_grid_dimension = new Eint32[GridRank];\n");
   fprintf(opf, "+    g_grid_start = new Eint32[GridRank];\n");
   fprintf(opf, "+    g_grid_end = new Eint32[GridRank];\n");
   fprintf(opf, "+    for (i = 0; i < GridRank; i++) {\n");
   fprintf(opf, "+        g_grid_dimension[i] = (Eint32) GridDimension[i];\n");
   fprintf(opf, "+        g_grid_start[i] = (Eint32) GridStartIndex[i];\n");
   fprintf(opf, "+        g_grid_end[i] = (Eint32) GridEndIndex[i];\n");
   fprintf(opf, "+    }\n");
   fprintf(opf, "+    \n");
   fprintf(opf, "   /* Find fields: density, total energy, velocity1-3. */\n");
   fprintf(opf, "  \n");
   fprintf(opf, "   if (this->IdentifyPhysicalQuantities(DensNum, GENum, Vel1Num, Vel2Num,\n");
   fprintf(opf, "-				       Vel3Num, TENum) == FAIL) {\n");
   fprintf(opf, "+				       Vel3Num, TENum, G0Num, ZetaNum) == FAIL) { //Here G0 and Zeta must be initialized, but can change for universal usage... add a grackle rank as parameter\n");
   fprintf(opf, "     ENZO_FAIL(\"Error in IdentifyPhysicalQuantities.\\n\");\n");
   fprintf(opf, "   }\n");
   fprintf(opf, "  \n");
   fprintf(opf, "@@ -90,12 +90,11 @@\n");
   fprintf(opf, "   float *velocity1   = BaryonField[Vel1Num];\n");
   fprintf(opf, "   float *velocity2   = BaryonField[Vel2Num];\n");
   fprintf(opf, "   float *velocity3   = BaryonField[Vel3Num];\n");
   fprintf(opf, "-\n");
   fprintf(opf, "-  float *volumetric_heating_rate = NULL;\n");
   fprintf(opf, "-  float *specific_heating_rate   = NULL;\n");
   fprintf(opf, "-\n");
   fprintf(opf, "+  float *fuv_G0		 = BaryonField[G0Num];\n");
   fprintf(opf, "+  float *cr_Zeta		 = BaryonField[ZetaNum];\n");
   fprintf(opf, "+ \n");
   fprintf(opf, "   /* Compute the cooling time. */\n");
   fprintf(opf, "-\n");
   fprintf(opf, "+ \n");
   fprintf(opf, "   FLOAT a = 1.0, dadt;\n");
   fprintf(opf, "   float TemperatureUnits = 1, DensityUnits = 1, LengthUnits = 1,\n");
   fprintf(opf, "     VelocityUnits = 1, TimeUnits = 1, aUnits = 1;\n");
   fprintf(opf, "@@ -106,9 +105,6 @@\n");
   fprintf(opf, "     CosmologyComputeExpansionFactor(Time+0.5*dtFixed, &a, &dadt);\n");
   fprintf(opf, "  \n");
   fprintf(opf, "     aUnits = 1.0/(1.0 + InitialRedshift);\n");
   fprintf(opf, "-  } else if (RadiationFieldRedshift > -1){\n");
   fprintf(opf, "-    a        = 1.0 / (1.0 + RadiationFieldRedshift);\n");
   fprintf(opf, "-    aUnits   = 1.0;\n");
   fprintf(opf, "   }\n");
   fprintf(opf, "   float afloat = float(a);\n");
   fprintf(opf, " \n");
   fprintf(opf, "@@ -121,7 +117,6 @@\n");
   fprintf(opf, "   grackle_units.time_units           = (double) TimeUnits;\n");
   fprintf(opf, "   grackle_units.velocity_units       = (double) VelocityUnits;\n");
   fprintf(opf, "   grackle_units.a_units              = (double) aUnits;\n");
   fprintf(opf, "-  grackle_units.a_value              = (double) a;\n");
   fprintf(opf, " \n");
   fprintf(opf, "   /* Metal cooling codes. */\n");
   fprintf(opf, "  \n");
   fprintf(opf, "@@ -163,7 +158,7 @@\n");
   fprintf(opf, "  \n");
   fprintf(opf, "   int temp_thermal = FALSE;\n");
   fprintf(opf, "   float *thermal_energy;\n");
   fprintf(opf, "-  if ( UseMHD ){\n");
   fprintf(opf, "+  if (HydroMethod == MHD_RK){\n");
   fprintf(opf, "     iBx = FindField(Bfield1, FieldType, NumberOfBaryonFields);\n");
   fprintf(opf, "     iBy = FindField(Bfield2, FieldType, NumberOfBaryonFields);\n");
   fprintf(opf, "     iBz = FindField(Bfield3, FieldType, NumberOfBaryonFields);  \n");
   fprintf(opf, "@@ -186,7 +181,7 @@\n");
   fprintf(opf, "       if(GridRank > 2)\n");
   fprintf(opf, "         thermal_energy[i] -= 0.5 * POW(BaryonField[Vel3Num][i], 2.0);\n");
   fprintf(opf, " \n");
   fprintf(opf, "-      if( UseMHD ) {\n");
   fprintf(opf, "+      if(HydroMethod == MHD_RK) {\n");
   fprintf(opf, "         thermal_energy[i] -= 0.5 * (POW(BaryonField[iBx][i], 2.0) + \n");
   fprintf(opf, "                                     POW(BaryonField[iBy][i], 2.0) + \n");
   fprintf(opf, "                                     POW(BaryonField[iBz][i], 2.0)) / \n");
   fprintf(opf, "@@ -195,83 +190,26 @@\n");
   fprintf(opf, "     } // for (int i = 0; i < size; i++)\n");
   fprintf(opf, "   }\n");
   fprintf(opf, " \n");
   fprintf(opf, "-  //\n");
   fprintf(opf, "-  // Put code here to assign fields to volumetric or specific\n");
   fprintf(opf, "-  // heating rate pointers\n");
   fprintf(opf, "-  //\n");
   fprintf(opf, "-\n");
   fprintf(opf, "-  /* set up grackle fields object */\n");
   fprintf(opf, "-  grackle_field_data my_fields;\n");
   fprintf(opf, "-\n");
   fprintf(opf, "-  my_fields.grid_rank = (Eint32) GridRank;\n");
   fprintf(opf, "-  my_fields.grid_dimension = g_grid_dimension;\n");
   fprintf(opf, "-  my_fields.grid_start     = g_grid_start;\n");
   fprintf(opf, "-  my_fields.grid_end       = g_grid_end;\n");
   fprintf(opf, "-\n");
   fprintf(opf, "-  /* now add in the baryon fields */\n");
   fprintf(opf, "-  my_fields.density         = density;\n");
   fprintf(opf, "-  my_fields.internal_energy = thermal_energy;\n");
   fprintf(opf, "-  my_fields.x_velocity      = velocity1;\n");
   fprintf(opf, "-  my_fields.y_velocity      = velocity2;\n");
   fprintf(opf, "-  my_fields.z_velocity      = velocity3;\n");
   fprintf(opf, "-  my_fields.HI_density      = BaryonField[HINum];\n");
   fprintf(opf, "-  my_fields.HII_density     = BaryonField[HIINum];\n");
   fprintf(opf, "-  my_fields.HeI_density     = BaryonField[HeINum];\n");
   fprintf(opf, "-  my_fields.HeII_density    = BaryonField[HeIINum];\n");
   fprintf(opf, "-  my_fields.HeIII_density   = BaryonField[HeIIINum];\n");
   fprintf(opf, "-  my_fields.e_density       = BaryonField[DeNum];\n");
   fprintf(opf, "-\n");
   fprintf(opf, "-  my_fields.HM_density      = BaryonField[HMNum];\n");
   fprintf(opf, "-  my_fields.H2I_density     = BaryonField[H2INum];\n");
   fprintf(opf, "-  my_fields.H2II_density    = BaryonField[H2IINum];\n");
   fprintf(opf, "-\n");
   fprintf(opf, "-  my_fields.DI_density      = BaryonField[DINum];\n");
   fprintf(opf, "-  my_fields.DII_density     = BaryonField[DIINum];\n");
   fprintf(opf, "-  my_fields.HDI_density     = BaryonField[HDINum];\n");
   fprintf(opf, "-\n");
   fprintf(opf, "-  my_fields.metal_density   = MetalPointer;\n");
   fprintf(opf, "-\n");
   fprintf(opf, "-  my_fields.volumetric_heating_rate = volumetric_heating_rate;\n");
   fprintf(opf, "-  my_fields.specific_heating_rate   = specific_heating_rate;\n");
   fprintf(opf, "-\n");
   fprintf(opf, "-#ifdef TRANSFER\n");
   fprintf(opf, "-  /* Find RT fields */\n");
   fprintf(opf, "-  int kphHINum, kphHeINum, kphHeIINum, kdissH2INum,\n");
   fprintf(opf, "-        gammaNum;\n");
   fprintf(opf, "-\n");
   fprintf(opf, "-  IdentifyRadiativeTransferFields(kphHINum, gammaNum, kphHeINum,\n");
   fprintf(opf, "-                                  kphHeIINum, kdissH2INum);\n");
   fprintf(opf, "-\n");
   fprintf(opf, "-  /* unit conversion from Enzo RT units to CGS */\n");
   fprintf(opf, "-  const float ev2erg = 1.60217653E-12;\n");
   fprintf(opf, "-  float rtunits = ev2erg / TimeUnits;\n");
   fprintf(opf, "-\n");
   fprintf(opf, "-  if( RadiativeTransfer ){\n");
   fprintf(opf, "-    my_fields.RT_HI_ionization_rate   = BaryonField[kphHINum];\n");
   fprintf(opf, "-\n");
   fprintf(opf, "-    if (RadiativeTransferHydrogenOnly == FALSE){\n");
   fprintf(opf, "-      my_fields.RT_HeI_ionization_rate  = BaryonField[kphHeINum];\n");
   fprintf(opf, "-      my_fields.RT_HeII_ionization_rate = BaryonField[kphHeIINum];\n");
   fprintf(opf, "-    }\n");
   fprintf(opf, "-\n");
   fprintf(opf, "-    if (MultiSpecies > 1)\n");
   fprintf(opf, "-      my_fields.RT_H2_dissociation_rate = BaryonField[kdissH2INum];\n");
   fprintf(opf, "-\n");
   fprintf(opf, "-    /* need to convert to CGS units */\n");
   fprintf(opf, "-    for( i = 0; i < size; i++) BaryonField[gammaNum][i] *= rtunits;\n");
   fprintf(opf, "-\n");
   fprintf(opf, "-    my_fields.RT_heating_rate = BaryonField[gammaNum];\n");
   fprintf(opf, "-\n");
   fprintf(opf, "-  }\n");
   fprintf(opf, "-#endif // TRANSFER\n");
   fprintf(opf, "-\n");
   fprintf(opf, "   /* Call the chemistry solver. */\n");
   fprintf(opf, "-\n");
   fprintf(opf, "-  if (solve_chemistry(&grackle_units, &my_fields, (double) dtFixed) == FAIL){\n");
   fprintf(opf, "+    if (solve_chemistry(&grackle_units,\n");
   fprintf(opf, "+                      (double) afloat, (double) dtFixed,\n");
   fprintf(opf, "+                      (Eint32) GridRank, g_grid_dimension,\n");
   fprintf(opf, "+                      g_grid_start, g_grid_end,\n");
   fprintf(opf, "+                      density, thermal_energy,\n");
   fprintf(opf, "+                      velocity1, velocity2, velocity3,fuv_G0,cr_Zeta, //!! Here updated, hohoho\n");
   fprintf(opf, "+                      BaryonField[HINum],   BaryonField[HIINum], \n");
   fprintf(opf, "+                      BaryonField[HMNum],   BaryonField[HeINum], \n");
   fprintf(opf, "+                      BaryonField[HeIINum], BaryonField[HeIIINum],\n");
   fprintf(opf, "+                      BaryonField[H2INum],  BaryonField[H2IINum],\n");
   fprintf(opf, "+                      BaryonField[DINum],   BaryonField[DIINum], \n");
   fprintf(opf, "+                      BaryonField[HDINum],  BaryonField[DeNum], \n");
   fprintf(opf, "+                      MetalPointer) == FAIL) {\n");
   fprintf(opf, "     fprintf(stderr, \"Error in Grackle solve_chemistry.\\n\");\n");
   fprintf(opf, "     return FAIL;\n");
   fprintf(opf, "   }\n");
   fprintf(opf, " \n");
   fprintf(opf, "+  // Set the total energy appropriately for the updated thermal energy.\n");
   fprintf(opf, "+\n");
   fprintf(opf, "   if (HydroMethod != Zeus_Hydro) {\n");
   fprintf(opf, "     for (i = 0; i < size; i++) {\n");
   fprintf(opf, "       BaryonField[TENum][i] = thermal_energy[i] +\n");
   fprintf(opf, "@@ -281,7 +219,7 @@\n");
   fprintf(opf, "       if(GridRank > 2)\n");
   fprintf(opf, "         BaryonField[TENum][i] += 0.5 * POW(BaryonField[Vel3Num][i], 2.0);\n");
   fprintf(opf, " \n");
   fprintf(opf, "-      if( UseMHD ) {\n");
   fprintf(opf, "+      if(HydroMethod == MHD_RK) {\n");
   fprintf(opf, "         BaryonField[TENum][i] += 0.5 * (POW(BaryonField[iBx][i], 2.0) + \n");
   fprintf(opf, "                                         POW(BaryonField[iBy][i], 2.0) + \n");
   fprintf(opf, "                                         POW(BaryonField[iBz][i], 2.0)) / \n");
   fprintf(opf, "@@ -295,15 +233,6 @@\n");
   fprintf(opf, "     delete [] thermal_energy;\n");
   fprintf(opf, "   }\n");
   fprintf(opf, " \n");
   fprintf(opf, "-#ifdef TRANSFER\n");
   fprintf(opf, "-  if (RadiativeTransfer){\n");
   fprintf(opf, "-    /* convert the RT units back to Enzo */\n");
   fprintf(opf, "-    for(i = 0; i < size; i ++) BaryonField[gammaNum][i] /= rtunits;\n");
   fprintf(opf, "-\n");
   fprintf(opf, "-  }\n");
   fprintf(opf, "-#endif TRANSFER\n");
   fprintf(opf, "-\n");
   fprintf(opf, "-\n");
   fprintf(opf, "   delete [] TotalMetals;\n");
   fprintf(opf, "   delete [] g_grid_dimension;\n");
   fprintf(opf, "   delete [] g_grid_start;\n");
   fprintf(opf, "diff -r 240af05dd312 src/enzo/Grid_IdentifyPhysicalQuantities.C\n");
   fprintf(opf, "--- a/src/enzo/Grid_IdentifyPhysicalQuantities.C	Wed Dec 14 11:11:05 2016 -0500\n");
   fprintf(opf, "+++ b/src/enzo/Grid_IdentifyPhysicalQuantities.C	Sun Feb 12 16:17:50 2017 -0500\n");
   fprintf(opf, "@@ -263,6 +263,70 @@\n");
   fprintf(opf, " \n");
   fprintf(opf, " }\n");
   fprintf(opf, " \n");
   fprintf(opf, "+int grid::IdentifyPhysicalQuantities(int &DensNum, int &GENum, int &Vel1Num,\n");
   fprintf(opf, "+				     int &Vel2Num, int &Vel3Num, int &TENum, int &G0Num, int &ZetaNum)\n");
   fprintf(opf, "+{\n");
   fprintf(opf, "+ \n");
   fprintf(opf, "+  DensNum = GENum = Vel1Num = Vel2Num = Vel3Num = TENum = G0Num = ZetaNum = 0;\n");
   fprintf(opf, "+ \n");
   fprintf(opf, "+  /* Find Density, if possible. */\n");
   fprintf(opf, "+ \n");
   fprintf(opf, "+  if ((DensNum = FindField(Density, FieldType, NumberOfBaryonFields)) < 0) {\n");
   fprintf(opf, "+    ENZO_FAIL(\"GIPQ: Cannot find density.\");\n");
   fprintf(opf, "+  }\n");
   fprintf(opf, "+ \n");
   fprintf(opf, "+  /* Find Total energy, if possible. */\n");
   fprintf(opf, "+ \n");
   fprintf(opf, "+  if ((TENum = FindField(TotalEnergy, FieldType, NumberOfBaryonFields)) < 0) {\n");
   fprintf(opf, "+    if( EquationOfState != 1 )\n");
   fprintf(opf, "+      ENZO_FAIL(\"Cannot find total energy.\");\n");
   fprintf(opf, "+  }\n");
   fprintf(opf, "+ \n");
   fprintf(opf, "+  /* Find gas energy, if possible. */\n");
   fprintf(opf, "+ \n");
   fprintf(opf, "+  if (DualEnergyFormalism == TRUE)\n");
   fprintf(opf, "+    if ((GENum = FindField(InternalEnergy, FieldType,\n");
   fprintf(opf, "+			   NumberOfBaryonFields)) < 0) {\n");
   fprintf(opf, "+      ENZO_FAIL(\"Cannot find gas energy.\");\n");
   fprintf(opf, "+    }\n");
   fprintf(opf, "+ \n");
   fprintf(opf, "+  /* Find Velocity1, if possible. */\n");
   fprintf(opf, "+ \n");
   fprintf(opf, "+  if ((Vel1Num = FindField(Velocity1, FieldType, NumberOfBaryonFields)) < 0) {\n");
   fprintf(opf, "+    ENZO_FAIL(\"Cannot find Velocity1.\");\n");
   fprintf(opf, "+  }\n");
   fprintf(opf, "+ \n");
   fprintf(opf, "+  /* Find Velocity2, if possible. */\n");
   fprintf(opf, "+ \n");
   fprintf(opf, "+  if (GridRank > 1 || HydroMethod==HD_RK || HydroMethod == MHD_Li)\n");
   fprintf(opf, "+    if ((Vel2Num = FindField(Velocity2, FieldType,\n");
   fprintf(opf, "+			     NumberOfBaryonFields)) < 0) {\n");
   fprintf(opf, "+      ENZO_FAIL(\"Cannot find Velocity2.\");\n");
   fprintf(opf, "+    }\n");
   fprintf(opf, "+ \n");
   fprintf(opf, "+  /* Find Velocity3, if possible. */\n");
   fprintf(opf, "+ \n");
   fprintf(opf, "+  if (GridRank > 2 || HydroMethod==HD_RK || HydroMethod == MHD_Li)\n");
   fprintf(opf, "+    if ((Vel3Num = FindField(Velocity3, FieldType,\n");
   fprintf(opf, "+			     NumberOfBaryonFields)) == 0) {\n");
   fprintf(opf, "+      ENZO_FAIL(\"Cannot find Velocity3.\");\n");
   fprintf(opf, "+    }\n");
   fprintf(opf, "+  \n");
   fprintf(opf, "+  /* Find G0, if possible */\n");
   fprintf(opf, "+ \n");
   fprintf(opf, "+  if ((G0Num = FindField(G0, FieldType, NumberOfBaryonFields)) < 0) {\n");
   fprintf(opf, "+      ENZO_FAIL(\"Cannot find G0.\");\n");
   fprintf(opf, "+  }\n");
   fprintf(opf, "+\n");
   fprintf(opf, "+  /* Find Zeta, if possible */\n");
   fprintf(opf, "+ \n");
   fprintf(opf, "+  if ((ZetaNum = FindField(Zeta, FieldType, NumberOfBaryonFields)) < 0) {\n");
   fprintf(opf, "+      ENZO_FAIL(\"Cannot find Zeta.\");\n");
   fprintf(opf, "+  }\n");
   fprintf(opf, "+\n");
   fprintf(opf, "+  return SUCCESS;\n");
   fprintf(opf, "+}\n");
   fprintf(opf, "+\n");
   fprintf(opf, " int grid::IdentifyDrivingFields(int &Drive1Num, int &Drive2Num, int &Drive3Num)\n");
   fprintf(opf, " {\n");
   fprintf(opf, " \n");
   fprintf(opf, "diff -r 240af05dd312 src/enzo/Grid_MultiSpeciesHandler.C\n");
   fprintf(opf, "--- a/src/enzo/Grid_MultiSpeciesHandler.C	Wed Dec 14 11:11:05 2016 -0500\n");
   fprintf(opf, "+++ b/src/enzo/Grid_MultiSpeciesHandler.C	Sun Feb 12 16:17:50 2017 -0500\n");
   fprintf(opf, "@@ -31,7 +31,7 @@\n");
   fprintf(opf, "   LCAPERF_START(\"grid_MultiSpeciesHandler\");\n");
   fprintf(opf, " \n");
   fprintf(opf, " #ifdef USE_GRACKLE\n");
   fprintf(opf, "-  if (grackle_data->use_grackle == TRUE) {\n");
   fprintf(opf, "+  if (grackle_data.use_grackle == TRUE) {\n");
   fprintf(opf, "     if (this->GrackleWrapper() == FAIL) {\n");
   fprintf(opf, "       ENZO_FAIL(\"Error in GrackleWrapper.\\n\");\n");
   fprintf(opf, "     }\n");
   fprintf(opf, "diff -r 240af05dd312 src/enzo/InitializeNew.C\n");
   fprintf(opf, "--- a/src/enzo/InitializeNew.C	Wed Dec 14 11:11:05 2016 -0500\n");
   fprintf(opf, "+++ b/src/enzo/InitializeNew.C	Sun Feb 12 16:17:50 2017 -0500\n");
   fprintf(opf, "@@ -100,6 +100,8 @@\n");
   fprintf(opf, "                         TopGridData &MetaData);\n");
   fprintf(opf, " int GalaxySimulationInitialize(FILE *fptr, FILE *Outfptr, HierarchyEntry &TopGrid,\n");
   fprintf(opf, "                         TopGridData &MetaData, ExternalBoundary &Exterior);\n");
   fprintf(opf, "+int MyGalaxyInitialize(FILE *fptr, FILE *Outfptr, HierarchyEntry &TopGrid,\n");
   fprintf(opf, "+						TopGridData &MetaData);\n");
   fprintf(opf, " int TestGravitySphereInitialize(FILE *fptr, FILE *Outfptr,\n");
   fprintf(opf, " 			       HierarchyEntry &TopGrid, TopGridData &MetaData);\n");
   fprintf(opf, " int SphericalInfallInitialize(FILE *fptr, FILE *Outfptr,\n");
   fprintf(opf, "@@ -516,6 +518,10 @@\n");
   fprintf(opf, "   if (ProblemType == 31)\n");
   fprintf(opf, "     ret = GalaxySimulationInitialize(fptr, Outfptr, TopGrid, MetaData,Exterior);\n");
   fprintf(opf, " \n");
   fprintf(opf, "+  // 302) MyGalaxy\n");
   fprintf(opf, "+  if (ProblemType == 302)\n");
   fprintf(opf, "+	ret = MyGalaxyInitialize(fptr, Outfptr, TopGrid, MetaData);\n");
   fprintf(opf, "+\n");
   fprintf(opf, "   // 35) Shearing Box Simulation\n");
   fprintf(opf, "   if (ProblemType == 35) \n");
   fprintf(opf, "     ret = ShearingBoxInitialize(fptr, Outfptr, TopGrid, MetaData);\n");
   fprintf(opf, "diff -r 240af05dd312 src/enzo/Make.config.objects\n");
   fprintf(opf, "--- a/src/enzo/Make.config.objects	Wed Dec 14 11:11:05 2016 -0500\n");
   fprintf(opf, "+++ b/src/enzo/Make.config.objects	Sun Feb 12 16:17:50 2017 -0500\n");
   fprintf(opf, "@@ -15,6 +15,9 @@\n");
   fprintf(opf, " #-----------------------------------------------------------------------\n");
   fprintf(opf, " \n");
   fprintf(opf, " OBJS_CONFIG_LIB = \\\n");
   fprintf(opf, "+  MyGalaxyInitialize.o \\\n");
   fprintf(opf, "+  Grid_MyGalaxyInitializeGrid.o \\\n");
   fprintf(opf, "+  Grid_SetFloor_EvolveLevel.o\\\n");
   fprintf(opf, "   MHDLoopInit.o \\\n");
   fprintf(opf, "   Grid_MHDLoopInitGrid.o \\\n");
   fprintf(opf, "         acml_st1.o \\\n");
   fprintf(opf, "diff -r 240af05dd312 src/enzo/Make.mach.linux-gnu\n");
   fprintf(opf, "--- a/src/enzo/Make.mach.linux-gnu	Wed Dec 14 11:11:05 2016 -0500\n");
   fprintf(opf, "+++ b/src/enzo/Make.mach.linux-gnu	Sun Feb 12 16:17:50 2017 -0500\n");
   fprintf(opf, "@@ -13,16 +13,17 @@\n");
   fprintf(opf, " #\n");
   fprintf(opf, " #=======================================================================\n");
   fprintf(opf, " \n");
   fprintf(opf, "-MACH_TEXT  = Generic Ubuntu 8.04\n");
   fprintf(opf, "+MACH_TEXT  = Generic Linux\n");
   fprintf(opf, " MACH_VALID = 1\n");
   fprintf(opf, "-MACH_FILE  = Make.mach.ubuntu-hardy\n");
   fprintf(opf, "+MACH_FILE  = Make.mach.linux-gnu\n");
   fprintf(opf, " \n");
   fprintf(opf, " #-----------------------------------------------------------------------\n");
   fprintf(opf, " # Install paths (local variables)\n");
   fprintf(opf, " #-----------------------------------------------------------------------\n");
   fprintf(opf, " \n");
   fprintf(opf, "-LOCAL_HDF5_INSTALL = /usr/local/hdf5/1.8.2s\n");
   fprintf(opf, "-LOCAL_GRACKLE_INSTALL = /usr/local\n");
   fprintf(opf, "+LOCAL_LIBZ_INSTALL = /apps/gcc/5.2.0/libz/1.2.8\n");
   fprintf(opf, "+LOCAL_HDF5_INSTALL = /apps/hdf5/1.8.9\n");
   fprintf(opf, "+LOCAL_GRACKLE_INSTALL = /ufrc/tan/pg3552/local\n");
   fprintf(opf, " \n");
   fprintf(opf, " #-----------------------------------------------------------------------\n");
   fprintf(opf, " # Compiler settings\n");
   fprintf(opf, "@@ -78,12 +79,13 @@\n");
   fprintf(opf, " #-----------------------------------------------------------------------\n");
   fprintf(opf, " \n");
   fprintf(opf, " LOCAL_INCLUDES_MPI    = # MPI includes\n");
   fprintf(opf, "+LOCAL_INCLUDES_LIBZ   = -I$(LOCAL_LIBZ_INSTALL)/include # LIBZ includes\n");
   fprintf(opf, " LOCAL_INCLUDES_HDF5   = -I$(LOCAL_HDF5_INSTALL)/include # HDF5 includes\n");
   fprintf(opf, " LOCAL_INCLUDES_HYPRE  = # hypre includes\n");
   fprintf(opf, " LOCAL_INCLUDES_PAPI   = # PAPI includes\n");
   fprintf(opf, " LOCAL_INCLUDES_GRACKLE = -I$(LOCAL_GRACKLE_INSTALL)/include\n");
   fprintf(opf, " \n");
   fprintf(opf, "-MACH_INCLUDES         = $(LOCAL_INCLUDES_HDF5)\n");
   fprintf(opf, "+MACH_INCLUDES         = $(LOCAL_INCLUDES_HDF5) $(LOCAL_INCLUDES_LIBZ)\n");
   fprintf(opf, " MACH_INCLUDES_MPI     = $(LOCAL_INCLUDES_MPI)\n");
   fprintf(opf, " MACH_INCLUDES_HYPRE   = $(LOCAL_INCLUDES_HYPRE)\n");
   fprintf(opf, " MACH_INCLUDES_PAPI    = $(LOCAL_INCLUDES_PAPI)\n");
   fprintf(opf, "@@ -94,14 +96,15 @@\n");
   fprintf(opf, " #-----------------------------------------------------------------------\n");
   fprintf(opf, " \n");
   fprintf(opf, " LOCAL_LIBS_MPI    = # MPI libraries\n");
   fprintf(opf, "+LOCAL_LIBS_LIBZ   = -L$(LOCAL_LIBZ_INSTALL)/lib -lz\n");
   fprintf(opf, " LOCAL_LIBS_HDF5   = -L$(LOCAL_HDF5_INSTALL)/lib -lhdf5 -lz # HDF5 libraries\n");
   fprintf(opf, " LOCAL_LIBS_HYPRE  = # hypre libraries\n");
   fprintf(opf, " LOCAL_LIBS_PAPI   = # PAPI libraries\n");
   fprintf(opf, " LOCAL_LIBS_MACH   = -lgfortran # Machine-dependent libraries\n");
   fprintf(opf, " LOCAL_LIBS_GRACKLE = -L$(LOCAL_GRACKLE_INSTALL)/lib -lgrackle\n");
   fprintf(opf, " \n");
   fprintf(opf, "-MACH_LIBS         = $(LOCAL_LIBS_HDF5) $(LOCAL_LIBS_MACH)\n");
   fprintf(opf, "+MACH_LIBS         = $(LOCAL_LIBS_HDF5) $(LOCAL_LIBS_MACH) $(LOCAL_LIBS_LIBZ)\n");
   fprintf(opf, " MACH_LIBS_MPI     = $(LOCAL_LIBS_MPI)\n");
   fprintf(opf, " MACH_LIBS_HYPRE   = $(LOCAL_LIBS_HYPRE)\n");
   fprintf(opf, " MACH_LIBS_PAPI    = $(LOCAL_LIBS_PAPI)\n");
   fprintf(opf, "-MACH_LIBS_GRACKLE = $(LOCAL_LIBS_GRACKLE)\n");
   fprintf(opf, "\\ No newline at end of file\n");
   fprintf(opf, "+MACH_LIBS_GRACKLE = $(LOCAL_LIBS_GRACKLE)\n");
   fprintf(opf, "diff -r 240af05dd312 src/enzo/ReadParameterFile.C\n");
   fprintf(opf, "--- a/src/enzo/ReadParameterFile.C	Wed Dec 14 11:11:05 2016 -0500\n");
   fprintf(opf, "+++ b/src/enzo/ReadParameterFile.C	Sun Feb 12 16:17:50 2017 -0500\n");
   fprintf(opf, "@@ -534,6 +534,22 @@\n");
   fprintf(opf, " \n");
   fprintf(opf, " #ifdef USE_GRACKLE\n");
   fprintf(opf, "     /* Grackle chemistry parameters */\n");
   fprintf(opf, "+	// OLDHC\n");
   fprintf(opf, "+	ret += sscanf(line, \"use_grackle = %%d\", &grackle_data.use_grackle);\n");
   fprintf(opf, "+	ret += sscanf(line, \"with_radiative_cooling = %%d\",\n");
   fprintf(opf, "+					&grackle_data.with_radiative_cooling);\n");
   fprintf(opf, "+	if (sscanf(line, \"grackle_data_file = %%s\", dummy) == 1) {\n");
   fprintf(opf, "+		grackle_data.grackle_data_file = dummy;\n");
   fprintf(opf, "+		ret++;\n");
   fprintf(opf, "+	}\n");
   fprintf(opf, "+	ret += sscanf(line, \"UVbackground = %%d\", &grackle_data.UVbackground);\n");
   fprintf(opf, "+	ret += sscanf(line, \"Compton_xray_heating = %%d\",\n");
   fprintf(opf, "+					&grackle_data.Compton_xray_heating);\n");
   fprintf(opf, "+	ret += sscanf(line, \"LWbackground_intensity = %%lf\",\n");
   fprintf(opf, "+					&grackle_data.LWbackground_intensity);\n");
   fprintf(opf, "+	ret += sscanf(line, \"LWbackground_sawtooth_suppression = %%d\",\n");
   fprintf(opf, "+					&grackle_data.LWbackground_sawtooth_suppression);\n");
   fprintf(opf, "+	/*\n");
   fprintf(opf, "     ret += sscanf(line, \"use_grackle = %%d\", &grackle_data->use_grackle);\n");
   fprintf(opf, "     ret += sscanf(line, \"with_radiative_cooling = %%d\",\n");
   fprintf(opf, "                   &grackle_data->with_radiative_cooling);\n");
   fprintf(opf, "@@ -557,6 +573,7 @@\n");
   fprintf(opf, "                   &grackle_data->LWbackground_intensity);\n");
   fprintf(opf, "     ret += sscanf(line, \"LWbackground_sawtooth_suppression = %%d\",\n");
   fprintf(opf, "                   &grackle_data->LWbackground_sawtooth_suppression);\n");
   fprintf(opf, "+	*/\n");
   fprintf(opf, "     /********************************/\n");
   fprintf(opf, " #endif\n");
   fprintf(opf, "     ret += sscanf(line, \"RadiativeCooling = %%\"ISYM, &RadiativeCooling);\n");
   fprintf(opf, "@@ -648,6 +665,10 @@\n");
   fprintf(opf, " 		  &UseMinimumPressureSupport);\n");
   fprintf(opf, "     ret += sscanf(line, \"MinimumPressureSupportParameter = %%\"FSYM,\n");
   fprintf(opf, " 		  &MinimumPressureSupportParameter);\n");
   fprintf(opf, "+	ret += sscanf(line, \"UseGasTemperatureFloor = %%\"ISYM,\n");
   fprintf(opf, "+		  &UseGasTemperatureFloor);\n");
   fprintf(opf, "+	ret += sscanf(line, \"GasTemperatureFloor = %%\"FSYM,\n");
   fprintf(opf, "+		  &GasTemperatureFloor);\n");
   fprintf(opf, "     ret += sscanf(line, \"RefineByJeansLengthSafetyFactor = %%\"FSYM,\n");
   fprintf(opf, " 		  &RefineByJeansLengthSafetyFactor);\n");
   fprintf(opf, "     ret += sscanf(line, \"JeansRefinementColdTemperature = %%\"FSYM,\n");
   fprintf(opf, "@@ -1574,71 +1595,68 @@\n");
   fprintf(opf, "   }\n");
   fprintf(opf, " \n");
   fprintf(opf, " #ifdef USE_GRACKLE\n");
   fprintf(opf, "-  /* If using Grackle chemistry and cooling library, override all other \n");
   fprintf(opf, "+    /* If using Grackle chemistry and cooling library, override all other\n");
   fprintf(opf, "      cooling machinery and do a translation of some of the parameters. */\n");
   fprintf(opf, "-  if (grackle_data->use_grackle == TRUE) {\n");
   fprintf(opf, "-    // grackle_data->use_grackle already set\n");
   fprintf(opf, "-    // grackle_data->with_radiative_cooling already set\n");
   fprintf(opf, "-    // grackle_data->grackle_data_file already set\n");
   fprintf(opf, "-    // grackle_data->UVbackground already set\n");
   fprintf(opf, "-    // grackle_data->Compton_xray_heating already set\n");
   fprintf(opf, "-    // grackle_data->LWbackground_intensity already set\n");
   fprintf(opf, "-    // grackle_data->LWbackground_sawtooth_suppression already set\n");
   fprintf(opf, "-    grackle_data->Gamma                          = (double) Gamma;\n");
   fprintf(opf, "-    grackle_data->primordial_chemistry           = (Eint32) MultiSpecies;\n");
   fprintf(opf, "-    grackle_data->metal_cooling                  = (Eint32) MetalCooling;\n");
   fprintf(opf, "-    grackle_data->h2_on_dust                     = (Eint32) H2FormationOnDust;\n");
   fprintf(opf, "-    grackle_data->cmb_temperature_floor          = (Eint32) CloudyCoolingData.CMBTemperatureFloor;\n");
   fprintf(opf, "-    grackle_data->three_body_rate                = (Eint32) ThreeBodyRate;\n");
   fprintf(opf, "-    grackle_data->cie_cooling                    = (Eint32) CIECooling;\n");
   fprintf(opf, "-    grackle_data->h2_optical_depth_approximation = (Eint32) H2OpticalDepthApproximation;\n");
   fprintf(opf, "-    grackle_data->photoelectric_heating          = (Eint32) PhotoelectricHeating;\n");
   fprintf(opf, "-    grackle_data->photoelectric_heating_rate     = (double) PhotoelectricHeatingRate;\n");
   fprintf(opf, "-    grackle_data->NumberOfTemperatureBins        = (Eint32) CoolData.NumberOfTemperatureBins;\n");
   fprintf(opf, "-    grackle_data->CaseBRecombination             = (Eint32) RateData.CaseBRecombination;\n");
   fprintf(opf, "-    grackle_data->TemperatureStart               = (double) CoolData.TemperatureStart;\n");
   fprintf(opf, "-    grackle_data->TemperatureEnd                 = (double) CoolData.TemperatureEnd;\n");
   fprintf(opf, "-    grackle_data->NumberOfDustTemperatureBins    = (Eint32) RateData.NumberOfDustTemperatureBins;\n");
   fprintf(opf, "-    grackle_data->DustTemperatureStart           = (double) RateData.DustTemperatureStart;\n");
   fprintf(opf, "-    grackle_data->DustTemperatureEnd             = (double) RateData.DustTemperatureEnd;\n");
   fprintf(opf, "-    grackle_data->HydrogenFractionByMass         = (double) CoolData.HydrogenFractionByMass;\n");
   fprintf(opf, "-    grackle_data->DeuteriumToHydrogenRatio       = (double) CoolData.DeuteriumToHydrogenRatio;\n");
   fprintf(opf, "-    grackle_data->SolarMetalFractionByMass       = (double) CoolData.SolarMetalFractionByMass;\n");
   fprintf(opf, "-    grackle_data->use_radiative_transfer         = (Eint32) RadiativeTransfer;\n");
   fprintf(opf, "-    grackle_data->radiative_transfer_coupled_rate_solver = (Eint32) RadiativeTransferCoupledRateSolver;\n");
   fprintf(opf, "-    grackle_data->radiative_transfer_hydrogen_only       = (Eint32) RadiativeTransferHydrogenOnly;\n");
   fprintf(opf, "-\n");
   fprintf(opf, "-    // Initialize units structure.\n");
   fprintf(opf, "-    FLOAT a_value, dadt;\n");
   fprintf(opf, "-    a_value = 1.0;\n");
   fprintf(opf, "-    code_units grackle_units;\n");
   fprintf(opf, "-    grackle_units.a_units = 1.0;\n");
   fprintf(opf, "-    if (GetUnits(&DensityUnits, &LengthUnits, &TemperatureUnits,\n");
   fprintf(opf, "-                 &TimeUnits, &VelocityUnits, MetaData.Time) == FAIL) {\n");
   fprintf(opf, "-      ENZO_FAIL(\"Error in GetUnits.\\n\");\n");
   fprintf(opf, "-    }\n");
   fprintf(opf, "-    if (ComovingCoordinates) {\n");
   fprintf(opf, "-      if (CosmologyComputeExpansionFactor(MetaData.Time, &a_value, \n");
   fprintf(opf, "-                                          &dadt) == FAIL) {\n");
   fprintf(opf, "-        ENZO_FAIL(\"Error in CosmologyComputeExpansionFactors.\\n\");\n");
   fprintf(opf, "-      }\n");
   fprintf(opf, "-      grackle_units.a_units            = (double) (1.0 / (1.0 + InitialRedshift));\n");
   fprintf(opf, "-    }\n");
   fprintf(opf, "-    grackle_units.comoving_coordinates = (Eint32) ComovingCoordinates;\n");
   fprintf(opf, "-    grackle_units.density_units        = (double) DensityUnits;\n");
   fprintf(opf, "-    grackle_units.length_units         = (double) LengthUnits;\n");
   fprintf(opf, "-    grackle_units.time_units           = (double) TimeUnits;\n");
   fprintf(opf, "-    grackle_units.velocity_units       = (double) VelocityUnits;\n");
   fprintf(opf, "-    grackle_units.a_value              = (double) a_value;\n");
   fprintf(opf, "-\n");
   fprintf(opf, "-    // Initialize chemistry structure.\n");
   fprintf(opf, "-    if (initialize_chemistry_data(&grackle_units) == FAIL) {\n");
   fprintf(opf, "-      ENZO_FAIL(\"Error in Grackle initialize_chemistry_data.\\n\");\n");
   fprintf(opf, "-    }\n");
   fprintf(opf, "-  }  // if (grackle_data->use_grackle == TRUE)\n");
   fprintf(opf, "-\n");
   fprintf(opf, "+    if (grackle_data.use_grackle == TRUE) {\n");
   fprintf(opf, "+        // grackle_data.use_grackle already set\n");
   fprintf(opf, "+        // grackle_data.with_radiative_cooling already set\n");
   fprintf(opf, "+        // grackle_data.grackle_data_file already set\n");
   fprintf(opf, "+        // grackle_data.UVbackground already set\n");
   fprintf(opf, "+        // grackle_data.Compton_xray_heating already set\n");
   fprintf(opf, "+        // grackle_data.LWbackground_intensity already set\n");
   fprintf(opf, "+        // grackle_data.LWbackground_sawtooth_suppression already set\n");
   fprintf(opf, "+        grackle_data.Gamma                          = (double) Gamma;\n");
   fprintf(opf, "+        grackle_data.primordial_chemistry           = (Eint32) MultiSpecies;\n");
   fprintf(opf, "+        grackle_data.metal_cooling                  = (Eint32) MetalCooling;\n");
   fprintf(opf, "+        grackle_data.h2_on_dust                     = (Eint32) H2FormationOnDust;\n");
   fprintf(opf, "+        grackle_data.cmb_temperature_floor          = (Eint32) CloudyCoolingData.CMBTemperatureFloor;\n");
   fprintf(opf, "+        grackle_data.three_body_rate                = (Eint32) ThreeBodyRate;\n");
   fprintf(opf, "+        grackle_data.cie_cooling                    = (Eint32) CIECooling;\n");
   fprintf(opf, "+        grackle_data.h2_optical_depth_approximation = (Eint32) H2OpticalDepthApproximation;\n");
   fprintf(opf, "+        grackle_data.photoelectric_heating          = (Eint32) PhotoelectricHeating;\n");
   fprintf(opf, "+        grackle_data.photoelectric_heating_rate     = (double) PhotoelectricHeatingRate;\n");
   fprintf(opf, "+        grackle_data.NumberOfTemperatureBins        = (Eint32) CoolData.NumberOfTemperatureBins;\n");
   fprintf(opf, "+        grackle_data.CaseBRecombination             = (Eint32) RateData.CaseBRecombination;\n");
   fprintf(opf, "+        grackle_data.TemperatureStart               = (double) CoolData.TemperatureStart;\n");
   fprintf(opf, "+        grackle_data.TemperatureEnd                 = (double) CoolData.TemperatureEnd;\n");
   fprintf(opf, "+        grackle_data.NumberOfDustTemperatureBins    = (Eint32) RateData.NumberOfDustTemperatureBins;\n");
   fprintf(opf, "+        grackle_data.DustTemperatureStart           = (double) RateData.DustTemperatureStart;\n");
   fprintf(opf, "+        grackle_data.DustTemperatureEnd             = (double) RateData.DustTemperatureEnd;\n");
   fprintf(opf, "+        grackle_data.HydrogenFractionByMass         = (double) CoolData.HydrogenFractionByMass;\n");
   fprintf(opf, "+        grackle_data.DeuteriumToHydrogenRatio       = (double) CoolData.DeuteriumToHydrogenRatio;\n");
   fprintf(opf, "+        grackle_data.SolarMetalFractionByMass       = (double) CoolData.SolarMetalFractionByMass;\n");
   fprintf(opf, "+        \n");
   fprintf(opf, "+        // Initialize units structure.\n");
   fprintf(opf, "+        FLOAT a_value, dadt;\n");
   fprintf(opf, "+        a_value = 1.0;\n");
   fprintf(opf, "+        code_units grackle_units;\n");
   fprintf(opf, "+        grackle_units.a_units = 1.0;\n");
   fprintf(opf, "+        if (GetUnits(&DensityUnits, &LengthUnits, &TemperatureUnits,\n");
   fprintf(opf, "+                     &TimeUnits, &VelocityUnits, MetaData.Time) == FAIL) {\n");
   fprintf(opf, "+            ENZO_FAIL(\"Error in GetUnits.\\n\");\n");
   fprintf(opf, "+        }\n");
   fprintf(opf, "+        if (ComovingCoordinates) {\n");
   fprintf(opf, "+            if (CosmologyComputeExpansionFactor(MetaData.Time, &a_value,\n");
   fprintf(opf, "+                                                &dadt) == FAIL) {\n");
   fprintf(opf, "+                ENZO_FAIL(\"Error in CosmologyComputeExpansionFactors.\\n\");\n");
   fprintf(opf, "+            }\n");
   fprintf(opf, "+            grackle_units.a_units            = (double) (1.0 / (1.0 + InitialRedshift));\n");
   fprintf(opf, "+        }\n");
   fprintf(opf, "+        grackle_units.comoving_coordinates = (Eint32) ComovingCoordinates;\n");
   fprintf(opf, "+        grackle_units.density_units        = (double) DensityUnits;\n");
   fprintf(opf, "+        grackle_units.length_units         = (double) LengthUnits;\n");
   fprintf(opf, "+        grackle_units.time_units           = (double) TimeUnits;\n");
   fprintf(opf, "+        grackle_units.velocity_units       = (double) VelocityUnits;\n");
   fprintf(opf, "+        \n");
   fprintf(opf, "+        // Initialize chemistry structure.\n");
   fprintf(opf, "+        if (initialize_chemistry_data(&grackle_units,\n");
   fprintf(opf, "+                                      (double) a_value) == FAIL) {\n");
   fprintf(opf, "+            ENZO_FAIL(\"Error in Grackle initialize_chemistry_data.\\n\");\n");
   fprintf(opf, "+        }\n");
   fprintf(opf, "+    }  // if (grackle_data.use_grackle == TRUE)\n");
   fprintf(opf, "+    \n");
   fprintf(opf, "   else {\n");
   fprintf(opf, "-#endif // USE_GRACKE\n");
   fprintf(opf, "+#endif // USE_GRACKLE\n");
   fprintf(opf, " \n");
   fprintf(opf, "     /* If GadgetEquilibriumCooling == TRUE, we don't want MultiSpecies\n");
   fprintf(opf, "        or RadiationFieldType to be on - both are taken care of in\n");
   fprintf(opf, "diff -r 240af05dd312 src/enzo/SetDefaultGlobalValues.C\n");
   fprintf(opf, "--- a/src/enzo/SetDefaultGlobalValues.C	Wed Dec 14 11:11:05 2016 -0500\n");
   fprintf(opf, "+++ b/src/enzo/SetDefaultGlobalValues.C	Sun Feb 12 16:17:50 2017 -0500\n");
   fprintf(opf, "@@ -489,34 +489,31 @@\n");
   fprintf(opf, "   CloudyCoolingData.CloudyElectronFractionFactor = 9.153959e-3; // calculated using Cloudy 07.02 abundances\n");
   fprintf(opf, " \n");
   fprintf(opf, " #ifdef USE_GRACKLE\n");
   fprintf(opf, "-    // Grackle chemistry data structure.\n");
   fprintf(opf, "-  chemistry_data *my_chemistry;\n");
   fprintf(opf, "-  my_chemistry = new chemistry_data;\n");
   fprintf(opf, "-  if (set_default_chemistry_parameters(my_chemistry) == FAIL) {\n");
   fprintf(opf, "-    ENZO_FAIL(\"Error in grackle: set_default_chemistry_parameters\\n\");\n");
   fprintf(opf, "-  }\n");
   fprintf(opf, "-\n");
   fprintf(opf, "-  // Map Grackle defaults to corresponding Enzo parameters\n");
   fprintf(opf, "-  Gamma                                 = (float) grackle_data->Gamma;\n");
   fprintf(opf, "-  MultiSpecies                          = (int) grackle_data->primordial_chemistry;\n");
   fprintf(opf, "-  MetalCooling                          = (int) grackle_data->metal_cooling;\n");
   fprintf(opf, "-  H2FormationOnDust                     = (int) grackle_data->h2_on_dust;\n");
   fprintf(opf, "-  CloudyCoolingData.CMBTemperatureFloor = (int) grackle_data->cmb_temperature_floor;\n");
   fprintf(opf, "-  ThreeBodyRate                         = (int) grackle_data->three_body_rate;\n");
   fprintf(opf, "-  CIECooling                            = (int) grackle_data->cie_cooling;\n");
   fprintf(opf, "-  H2OpticalDepthApproximation           = (int) grackle_data->h2_optical_depth_approximation;\n");
   fprintf(opf, "-  PhotoelectricHeating                  = (int) grackle_data->photoelectric_heating;\n");
   fprintf(opf, "-  PhotoelectricHeatingRate              = (float) grackle_data->photoelectric_heating_rate;\n");
   fprintf(opf, "-  CoolData.NumberOfTemperatureBins      = (int) grackle_data->NumberOfTemperatureBins;\n");
   fprintf(opf, "-  RateData.CaseBRecombination           = (int) grackle_data->CaseBRecombination;\n");
   fprintf(opf, "-  CoolData.TemperatureStart             = (float) grackle_data->TemperatureStart;\n");
   fprintf(opf, "-  CoolData.TemperatureEnd               = (float) grackle_data->TemperatureEnd;\n");
   fprintf(opf, "-  RateData.NumberOfDustTemperatureBins  = (int) grackle_data->NumberOfDustTemperatureBins;\n");
   fprintf(opf, "-  RateData.DustTemperatureStart         = (float) grackle_data->DustTemperatureStart;\n");
   fprintf(opf, "-  RateData.DustTemperatureEnd           = (float) grackle_data->DustTemperatureEnd;\n");
   fprintf(opf, "-  CoolData.HydrogenFractionByMass       = (float) grackle_data->HydrogenFractionByMass;\n");
   fprintf(opf, "-  CoolData.DeuteriumToHydrogenRatio     = (float) grackle_data->DeuteriumToHydrogenRatio;\n");
   fprintf(opf, "-  CoolData.SolarMetalFractionByMass     = (float) grackle_data->SolarMetalFractionByMass;\n");
   fprintf(opf, "+    // Grackle chemistry data structure. // OLDHC\n");
   fprintf(opf, "+    if (set_default_chemistry_parameters() == FAIL) {\n");
   fprintf(opf, "+        ENZO_FAIL(\"Error in grackle: set_default_chemistry_parameters\\n\");\n");
   fprintf(opf, "+    }\n");
   fprintf(opf, "+    // Map Grackle defaults to corresponding Enzo parameters\n");
   fprintf(opf, "+    Gamma                                 = (float) grackle_data.Gamma;\n");
   fprintf(opf, "+    MultiSpecies                          = (int) grackle_data.primordial_chemistry;\n");
   fprintf(opf, "+    MetalCooling                          = (int) grackle_data.metal_cooling;\n");
   fprintf(opf, "+    H2FormationOnDust                     = (int) grackle_data.h2_on_dust;\n");
   fprintf(opf, "+    CloudyCoolingData.CMBTemperatureFloor = (int) grackle_data.cmb_temperature_floor;\n");
   fprintf(opf, "+    ThreeBodyRate                         = (int) grackle_data.three_body_rate;\n");
   fprintf(opf, "+    CIECooling                            = (int) grackle_data.cie_cooling;\n");
   fprintf(opf, "+    H2OpticalDepthApproximation           = (int) grackle_data.h2_optical_depth_approximation;\n");
   fprintf(opf, "+    PhotoelectricHeating                  = (int) grackle_data.photoelectric_heating;\n");
   fprintf(opf, "+    PhotoelectricHeatingRate              = (float) grackle_data.photoelectric_heating_rate;\n");
   fprintf(opf, "+    CoolData.NumberOfTemperatureBins      = (int) grackle_data.NumberOfTemperatureBins;\n");
   fprintf(opf, "+    RateData.CaseBRecombination           = (int) grackle_data.CaseBRecombination;\n");
   fprintf(opf, "+    CoolData.TemperatureStart             = (float) grackle_data.TemperatureStart;\n");
   fprintf(opf, "+    CoolData.TemperatureEnd               = (float) grackle_data.TemperatureEnd;\n");
   fprintf(opf, "+    RateData.NumberOfDustTemperatureBins  = (int) grackle_data.NumberOfDustTemperatureBins;\n");
   fprintf(opf, "+    RateData.DustTemperatureStart         = (float) grackle_data.DustTemperatureStart;\n");
   fprintf(opf, "+    RateData.DustTemperatureEnd           = (float) grackle_data.DustTemperatureEnd;\n");
   fprintf(opf, "+    CoolData.HydrogenFractionByMass       = (float) grackle_data.HydrogenFractionByMass;\n");
   fprintf(opf, "+    CoolData.DeuteriumToHydrogenRatio     = (float) grackle_data.DeuteriumToHydrogenRatio;\n");
   fprintf(opf, "+    CoolData.SolarMetalFractionByMass     = (float) grackle_data.SolarMetalFractionByMass;\n");
   fprintf(opf, " #endif\n");
   fprintf(opf, " \n");
   fprintf(opf, "   OutputCoolingTime = FALSE;\n");
   fprintf(opf, "@@ -532,7 +529,8 @@\n");
   fprintf(opf, "   ZEUSQuadraticArtificialViscosity = 2.0;\n");
   fprintf(opf, "   UseMinimumPressureSupport        = FALSE;\n");
   fprintf(opf, "   MinimumPressureSupportParameter  = 100.0;\n");
   fprintf(opf, "- \n");
   fprintf(opf, "+  UseGasTemperatureFloor           = FALSE;\n");
   fprintf(opf, "+  GasTemperatureFloor              = 300.0;\n");
   fprintf(opf, "   //MinimumSlopeForRefinement        = 0.3;          // 30%% change in value\n");
   fprintf(opf, "   MinimumShearForRefinement        = 1.0;          //AK\n");
   fprintf(opf, "   OldShearMethod                   = 0;            \n");
   fprintf(opf, "diff -r 240af05dd312 src/enzo/WriteParameterFile.C\n");
   fprintf(opf, "--- a/src/enzo/WriteParameterFile.C	Wed Dec 14 11:11:05 2016 -0500\n");
   fprintf(opf, "+++ b/src/enzo/WriteParameterFile.C	Sun Feb 12 16:17:50 2017 -0500\n");
   fprintf(opf, "@@ -491,19 +491,15 @@\n");
   fprintf(opf, "   if (DrivenFlowProfile)\n");
   fprintf(opf, "     Forcing.WriteParameters(fptr);\n");
   fprintf(opf, " #ifdef USE_GRACKLE\n");
   fprintf(opf, "-  /* Grackle chemistry parameters */\n");
   fprintf(opf, "-  fprintf(fptr, \"use_grackle                 = %%d\\n\", grackle_data->use_grackle);\n");
   fprintf(opf, "-  fprintf(fptr, \"with_radiative_cooling      = %%d\\n\", grackle_data->with_radiative_cooling);\n");
   fprintf(opf, "-  fprintf(fptr, \"use_volumetric_heating_rate = %%d\\n\", grackle_data->use_volumetric_heating_rate);\n");
   fprintf(opf, "-  fprintf(fptr, \"use_specific_heating_rate   = %%d\\n\", grackle_data->use_specific_heating_rate);\n");
   fprintf(opf, "-  fprintf(fptr, \"self_shielding_method       = %%d\\n\", grackle_data->self_shielding_method);\n");
   fprintf(opf, "-  fprintf(fptr, \"radiative_transfer_intermediate_step = %%d\\n\", grackle_data->radiative_transfer_intermediate_step);\n");
   fprintf(opf, "-  fprintf(fptr, \"grackle_data_file           = %%s\\n\", grackle_data->grackle_data_file);\n");
   fprintf(opf, "-  fprintf(fptr, \"UVbackground                = %%d\\n\", grackle_data->UVbackground);\n");
   fprintf(opf, "-  fprintf(fptr, \"Compton_xray_heating        = %%d\\n\", grackle_data->Compton_xray_heating);\n");
   fprintf(opf, "-  fprintf(fptr, \"LWbackground_intensity      = %%lf\\n\", grackle_data->LWbackground_intensity);\n");
   fprintf(opf, "-  fprintf(fptr, \"LWbackground_sawtooth_suppression = %%d\\n\", grackle_data->LWbackground_sawtooth_suppression);\n");
   fprintf(opf, "-  /********************************/\n");
   fprintf(opf, "+    /* Grackle chemistry parameters */\n");
   fprintf(opf, "+    fprintf(fptr, \"use_grackle                 = %%d\\n\", grackle_data.use_grackle);\n");
   fprintf(opf, "+    fprintf(fptr, \"with_radiative_cooling      = %%d\\n\", grackle_data.with_radiative_cooling);\n");
   fprintf(opf, "+    fprintf(fptr, \"grackle_data_file           = %%s\\n\", grackle_data.grackle_data_file);\n");
   fprintf(opf, "+    fprintf(fptr, \"UVbackground                = %%d\\n\", grackle_data.UVbackground);\n");
   fprintf(opf, "+    fprintf(fptr, \"Compton_xray_heating        = %%d\\n\", grackle_data.Compton_xray_heating);\n");
   fprintf(opf, "+    fprintf(fptr, \"LWbackground_intensity      = %%lf\\n\", grackle_data.LWbackground_intensity);\n");
   fprintf(opf, "+    fprintf(fptr, \"LWbackground_sawtooth_suppression = %%d\\n\", grackle_data.LWbackground_sawtooth_suppression);\n");
   fprintf(opf, "+    /********************************/\n");
   fprintf(opf, " #endif\n");
   fprintf(opf, "   fprintf(fptr, \"RadiativeCooling               = %%\"ISYM\"\\n\", RadiativeCooling);\n");
   fprintf(opf, "   fprintf(fptr, \"RadiativeCoolingModel          = %%\"ISYM\"\\n\", RadiativeCoolingModel);\n");
   fprintf(opf, "@@ -601,6 +597,10 @@\n");
   fprintf(opf, " 	  UseMinimumPressureSupport);\n");
   fprintf(opf, "   fprintf(fptr, \"MinimumPressureSupportParameter  = %%\"FSYM\"\\n\",\n");
   fprintf(opf, " 	  MinimumPressureSupportParameter);\n");
   fprintf(opf, "+  fprintf(fptr, \"UseGasTemperatureFloor = %%\"ISYM\"\\n\",\n");
   fprintf(opf, "+	  UseGasTemperatureFloor);\n");
   fprintf(opf, "+  fprintf(fptr, \"GasTemperatureFloor = %%\"FSYM\"\\n\",\n");
   fprintf(opf, "+	  GasTemperatureFloor);\n");
   fprintf(opf, "   fprintf(fptr, \"RefineByJeansLengthSafetyFactor  = %%\"FSYM\"\\n\",\n");
   fprintf(opf, " 	  RefineByJeansLengthSafetyFactor);\n");
   fprintf(opf, "   fprintf(fptr, \"JeansRefinementColdTemperature  = %%\"FSYM\"\\n\",\n");
   fprintf(opf, "diff -r 240af05dd312 src/enzo/global_data.h\n");
   fprintf(opf, "--- a/src/enzo/global_data.h	Wed Dec 14 11:11:05 2016 -0500\n");
   fprintf(opf, "+++ b/src/enzo/global_data.h	Sun Feb 12 16:17:50 2017 -0500\n");
   fprintf(opf, "@@ -502,6 +502,10 @@\n");
   fprintf(opf, " EXTERN int UseMinimumPressureSupport;\n");
   fprintf(opf, " EXTERN float MinimumPressureSupportParameter;\n");
   fprintf(opf, " \n");
   fprintf(opf, "+/* Parameters for GasTemperatureFloor.*/\n");
   fprintf(opf, "+EXTERN int UseGasTemperatureFloor;\n");
   fprintf(opf, "+EXTERN float GasTemperatureFloor;\n");
   fprintf(opf, "+\n");
   fprintf(opf, " /* Parameters for statically refined regions. */\n");
   fprintf(opf, " EXTERN FLOAT StaticRefineRegionLeftEdge[MAX_STATIC_REGIONS][MAX_DIMENSION];\n");
   fprintf(opf, " EXTERN FLOAT StaticRefineRegionRightEdge[MAX_STATIC_REGIONS][MAX_DIMENSION];\n");
   fprintf(opf, "diff -r 240af05dd312 src/enzo/typedefs.h\n");
   fprintf(opf, "--- a/src/enzo/typedefs.h	Wed Dec 14 11:11:05 2016 -0500\n");
   fprintf(opf, "+++ b/src/enzo/typedefs.h	Sun Feb 12 16:17:50 2017 -0500\n");
   fprintf(opf, "@@ -169,8 +169,10 @@\n");
   fprintf(opf, " \n");
   fprintf(opf, "   /* Cosmic Ray Energy Density */\n");
   fprintf(opf, "   CRDensity = 97,\n");
   fprintf(opf, "-\n");
   fprintf(opf, "-  FieldUndefined  = 98;\n");
   fprintf(opf, "+  /* pre-set (or evolved) FUV radiation field (G0) */\n");
   fprintf(opf, "+  G0 = 98,\n");
   fprintf(opf, "+  Zeta = 99,\n");
   fprintf(opf, "+  FieldUndefined  = 100;\n");
   fprintf(opf, " \n");
   fprintf(opf, " /*\n");
   fprintf(opf, " enum field_type {Density, TotalEnergy, InternalEnergy, Pressure,\n");
   fprintf(opf, "\n");
   fclose(opf);
}
